### ISSUE TITLE
[Suggestion] Add enchantment detail support for WAILA/HWYLA

### ISSUE THREAD

**Issue by ThePromisedLAN** [Drullkus/Shield-Parry#6]
Pretty self explanatory. Shield Parry enchantments (or just Rebound, currently) should come with a quick description like other vanilla enchantments when holding shift to view enchantment descriptions in WAILA.

https://puu.sh/Aqzih.png

**Comment by Drullkus** [comment]
The mod dev added an easy loc key for me to use! Excellent, will add in next update.

**Comment by CREEATION** [comment]
Any news on this? 🐢 Would make it work with [Enchantment Descriptions](https://minecraft.curseforge.com/projects/enchantment-descriptions), too.
