### ISSUE TITLE
Arrows render weird client side

### ISSUE THREAD

**Issue by MissPotato** [Drullkus/Shield-Parry#8]
This isn't surprising as arrows are already incredibly buggy client side in Vanilla but deflecting an arrow causes it to hit the ground making it hard to tell if you successfully parried. Maybe a workaround would be a distinct sound that plays when you parry and hide the arrow entirely the tick before it hits the player?

**Comment by ghost** [comment]
Up

**Comment by ghost** [comment]
Fixed?
